---
title             : "Lab 8 Group Committing to github"
shorttitle        : "pay no attention to the tibble behind the curtain..."

author: 
  - name          : "Janette Avelar"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Oregon, USA"
    email         : "javelar7@uoregon.edu"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Writing - Review & Committing
  - name          : "David Fainstein"
    affiliation   : "1"
    role:
      - Writing - Review & Committing
  - name          : "Joe Swinehart"
    affiliation   : "1"
    role:
      - Writing - Review & Committing
  - name          : "Makayla Whitney"
    affiliation   : "1"
    role:
      - Writing - Review & Committing

affiliation:
  - id            : "1"
    institution   : "University of Oregon"


authornote: |
  Janette Avelar, University of Oregon College of Education,
  David Fainstein, University of Oregon College of Education,
  Joe Swinehart, Behavioral Research & Teaching,
  Makayla Whitney, University of Oregon College of Education

  Project completed using RStudio, GitKraken, GitHub, and papaja
  
  Contact: javelar7@uoregon.edu

abstract: |
  This project aims to explore the relationship between teacher experience and student math scores, with an additional look at how free/reduced price lunch status correpsonds to that relationship.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "teacher, experience, lunch, math, scores"

bibliography      : ["r-references.bib"]

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(echo = FALSE,
                      eval = TRUE,
                      fig.width = 6.5,
                      fig.height = 8)
```

``` {r loading in data}
library(here)
library(rio)
library(tidyverse)
star <- import(here("data", "star.csv"))
```

``` {r tablecode, results = "asis"}

star <- star %>% 
  mutate(stand_math = (tmathss - mean(tmathss)) / sd(tmathss),
         stand_rdg  = (treadss - mean(treadss)) / sd(treadss))

star %>% 
  group_by(sex, frl) %>% 
  summarize(math_mean = mean(tmathss),
            math_sd = sd(tmathss),
            read_mean = mean(treadss),
            read_ss = sd(treadss)) %>%
  papaja::apa_table()
```

\newpage

``` {r graph}

ggplot(star, aes(totexp, tmathss)) +
  geom_point(color = "gray40") +
  geom_smooth(method = "lm", aes(color = frl)) +
  labs(x = "Teacher Experience (years)",
       y = "Total Math Scale Score",
       title = "Relation between teacher experience and math scores",
       subtitle = "Separate regression lines displayed by free/reduced lunch status") +
  theme(legend.position = "bottom") +
  guides(fill = "none") +
  scale_fill_discrete(name = "Lunch status", labels = c("Free/Reduced Price Meals", "Paid Meals"))


```




# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
